using System;
using System.Collections.Generic;

namespace ScreenPowerPro.Services;

/// <summary>
/// ScreenPowerPro çoklu dil (Türkçe ve İngilizce) yönetim servisi.
/// Çalışma anında anında dil değişimini destekler ve tüm arayüzü günceller.
/// </summary>
public class LocalizationService
{
    private readonly SettingsService _settingsService;
    private string _currentLanguage = "tr";

    public string CurrentLanguage => _currentLanguage;

    public event Action? LanguageChanged;

    private readonly Dictionary<string, string> _tr = new(StringComparer.OrdinalIgnoreCase)
    {
        // Genel & Ortak
        { "AppTitle", "ScreenPowerPro" },
        { "Save", "Kaydet" },
        { "Cancel", "İptal" },
        { "Delete", "Sil" },
        { "Close", "Kapat" },
        { "Back", "Geri Dön" },
        { "Success", "Başarılı" },
        { "Error", "Hata" },
        { "Warning", "Uyarı" },
        { "Loading", "Yükleniyor..." },
        { "Reset", "Sıfırla" },
        { "None", "Yok" },
        { "Default", "Varsayılan" },
        { "Browse", "Gözat" },
        { "Open", "Aç" },
        { "Rename", "Yeniden Adlandır" },
        { "Refresh", "Yenile" },
        { "Format", "Format" },
        { "Resolution", "Çözünürlük" },
        { "Fps", "Kare Hızı (FPS)" },

        // Dashboard
        { "Dashboard_Header_History", "Geçmiş" },
        { "Dashboard_Header_ProjectManager", "Proje Yöneticisi" },
        { "Dashboard_Header_Settings", "Ayarlar" },
        { "Dashboard_Header_Teleprompter", "Teleprompter" },
        { "Dashboard_Subtitle", "Neyi kaydetmek istersiniz?" },
        { "Dashboard_Mode_Screen", "Tam Ekran" },
        { "Dashboard_Mode_Screen_Desc", "Birincil ekranın tamamını yüksek kalitede kaydeder." },
        { "Dashboard_Mode_Custom", "Özel Bölge" },
        { "Dashboard_Mode_Custom_Desc", "Ekranda dilediğiniz bir bölgeyi piksel hassasiyetinde seçin." },
        { "Dashboard_Mode_Window", "Uygulama Penceresi" },
        { "Dashboard_Mode_Window_Desc", "Açık olan belirli bir uygulamayı veya pencereyi hedefleyin." },
        { "Dashboard_Mode_Camera", "Sadece Kamera" },
        { "Dashboard_Mode_Camera_Desc", "Yalnızca web kamerasını tam ekran veya daire modunda kaydeder." },
        { "Dashboard_Device_Camera", "Kamera" },
        { "Dashboard_Device_Mic", "Mikrofon" },
        { "Dashboard_Device_SystemAudio", "Sistem Sesi" },
        { "Dashboard_StartRecording", "Kayıt Başlat" },
        { "Dashboard_SelectWindow", "Pencere Seçin" },
        { "Dashboard_OnlyAppAudio", "Yalnızca Uygulama Sesi" },
        { "Dashboard_OnlyAppCount", "Yalnızca Uygulama ({0})" },
        { "Dashboard_NoAudioApps", "Açık ses uygulaması yok" },
        { "Dashboard_AllSystemAudio", "Tüm Sistem Sesi (Varsayılan)" },
        { "Dashboard_History_Title", "Kayıt Geçmişi" },
        { "Dashboard_History_TabRecordings", "Kayıtlar" },
        { "Dashboard_History_TabShared", "Paylaşılanlar" },
        { "Dashboard_History_Empty", "Henüz kayıtlı proje bulunamadı." },
        { "Dashboard_History_SharedEmpty", "Paylaşım geçmişi bulunamadı." },
        { "Dashboard_History_Open", "Projeyi Aç" },
        { "Dashboard_History_Rename", "Yeniden Adlandır" },
        { "Dashboard_History_ShowInFolder", "Klasörde Göster" },
        { "Dashboard_History_Delete", "Projeyi Sil" },
        { "Dashboard_History_DeleteConfirm", "\"{0}\" projesini ve tüm kayıt dosyalarını kalıcı olarak silmek istediğinizden emin misiniz?" },
        { "Dashboard_History_RenamePrompt", "Yeni proje adı girin" },
        { "Dashboard_History_ImportVideo", "Harici Video İçe Aktar" },

        // Settings (SettingsWindow & SettingsPage)
        { "Settings_Title", "Ayarlar" },
        { "Settings_Tab_General", "Genel" },
        { "Settings_Tab_Record", "Kayıt" },
        { "Settings_Tab_Shortcuts", "Kısayol Tuşları" },
        { "Settings_Tab_Export", "Dışa Aktar" },
        { "Settings_Language", "Uygulama Dili" },
        { "Settings_Language_TR", "Türkçe" },
        { "Settings_Language_EN", "English" },
        { "Settings_SaveLocation", "Kayıt Konumu" },
        { "Settings_ExportLocation", "Dışa Aktarma Konumu" },
        { "Settings_AutoStart", "Windows ile Birlikte Başlat" },
        { "Settings_AutoPlay", "Editör Açıldığında Videoyu Otomatik Oynat" },
        { "Settings_ExcludeApp", "ScreenPowerPro'yu Kendi Kaydından Gizle" },
        { "Settings_Quality", "Kayıt Kalitesi" },
        { "Settings_Quality_Ultra", "Ultra (Kayıpsıza Yakın)" },
        { "Settings_Quality_High", "Yüksek (Önerilen)" },
        { "Settings_Quality_Medium", "Orta" },
        { "Settings_Quality_Low", "Düşük" },
        { "Settings_Fps", "Hedef Kare Hızı (FPS)" },
        { "Settings_Resolution", "Kayıt Çözünürlüğü" },
        { "Settings_ZoomEffect", "Varsayılan Zoom Efekti" },
        { "Settings_Zoom_2D", "2D Zoom (Yumuşak)" },
        { "Settings_Zoom_3D", "3D Hareket (Anlık)" },
        { "Settings_Zoom_None", "Kapalı" },
        { "Settings_Countdown", "Kayıt Öncesi Geri Sayım Süresi" },
        { "Settings_Countdown_None", "Geri sayım yok" },
        { "Settings_Countdown_3s", "3 saniye" },
        { "Settings_Countdown_5s", "5 saniye" },
        { "Settings_Countdown_10s", "10 saniye" },
        { "Settings_HideDesktopIcons", "Kayıt Esnasında Masaüstü Simgelerini Gizle" },
        { "Settings_HideTaskbar", "Kayıt Esnasında Görev Çubuğunu Gizle" },
        { "Settings_HideMouseCursor", "Ham Kayıtta Fare İmlecini Gizle" },
        { "Settings_Shortcut_StartStop", "Kaydı Başlat / Durdur Kısayolu" },
        { "Settings_Shortcut_Pause", "Kaydı Duraklat / Devam Et Kısayolu" },
        { "Settings_Shortcut_Screenshot", "Ekran Görüntüsü Alma Kısayolu" },
        { "Settings_ExportFormat", "Varsayılan Dışa Aktarma Formatı" },
        { "Settings_ExportResolution", "Varsayılan Dışa Aktarma Çözünürlüğü" },
        { "Settings_SaveBtn", "Ayarları Kaydet" },
        { "Settings_SavedSuccess", "Ayarlar başarıyla kaydedildi." },

        // Editor
        { "Editor_Nav_Back", "Kayıt Paneli" },
        { "Editor_Nav_Save", "Kaydet" },
        { "Editor_Nav_Export", "Dışa Aktar" },
        { "Editor_Nav_Saved", "Proje Kaydedildi" },
        { "Editor_Sidebar_Cursor", "İmleç Ayarları" },
        { "Editor_Sidebar_Canvas", "Tuval Boyutu & Tarzı" },
        { "Editor_Sidebar_Audio", "Mikrofon & Ses" },
        { "Editor_Sidebar_Keys", "Kısayol Tuşları" },
        { "Editor_Sidebar_Motion", "Hareket & Bulanıklık" },
        { "Editor_Sidebar_Camera", "Kamera Yerleşimi" },
        { "Editor_Sidebar_Volume", "Ses Mikseri" },
        { "Editor_Sidebar_Watermark", "Filigran" },
        { "Editor_Sidebar_Zoom", "Zoom Özellikleri" },
        { "Editor_Cursor_Title", "İMLEÇ AYARLARI" },
        { "Editor_Cursor_Show", "İmleci Göster" },
        { "Editor_Cursor_Size", "İmleç Boyutu" },
        { "Editor_Cursor_Style", "İmleç Tarzı" },
        { "Editor_Cursor_ClickEffect", "Tıklama Efekti" },
        { "Editor_Cursor_ClickEffect_None", "Yok" },
        { "Editor_Cursor_ClickEffect_Default", "Varsayılan" },
        { "Editor_Cursor_ClickEffect_Ripple", "Dalga" },
        { "Editor_Cursor_ClickEffect_Ring", "Halka" },
        { "Editor_Cursor_ClickEffect_Diffusion", "Yayılma" },
        { "Editor_Cursor_ClickEffect_Spotlight", "Projektör" },
        { "Editor_Cursor_ClickEffect_Sparkle", "Pırıltı" },
        { "Editor_Cursor_ClickEffect_Firework", "Havai Fişek" },
        { "Editor_Cursor_ClickEffect_Christmas", "Yılbaşı" },
        { "Editor_Cursor_ClickSound", "Tıklama Sesi Çal" },
        { "Editor_Cursor_HideIdle", "Hareketsizken İmleci Gizle" },
        { "Editor_Cursor_RawInfoTitle", "Ham Kayıt Fare İmleci" },
        { "Editor_Cursor_RawInfoDesc", "Kayıt esnasında 'Ham Kayıtta Fare İmlecini Gizle' seçildiğinde videodaki orijinal imleç kaydedilmez ve yalnızca burada seçtiğiniz özel imleç görünür." },
        { "Editor_Canvas_Title", "TUVAL BOYUTU & TARZI" },
        { "Editor_Canvas_AspectRatio", "En-Boy Oranı" },
        { "Editor_Canvas_Auto", "Otomatik" },
        { "Editor_Canvas_FixedZoom", "Sabit Zoom Alanı" },
        { "Editor_Canvas_Padding", "Kenar Boşluğu" },
        { "Editor_Canvas_Inset", "İç Boşluk" },
        { "Editor_Canvas_Roundness", "Köşe Yuvarlaklığı" },
        { "Editor_Canvas_Shadow", "Gölge" },
        { "Editor_Canvas_BgPreset", "Arka Plan Önayarları" },
        { "Editor_Canvas_PresetDefault", "Varsayılan" },
        { "Editor_Canvas_PresetSteady", "Dengeli" },
        { "Editor_Canvas_PresetGraceful", "Zarif" },
        { "Editor_Canvas_PresetScenery", "Manzara" },
        { "Editor_Canvas_Opacity", "Opaklık" },
        { "Editor_Audio_Title", "MİKROFON & SES" },
        { "Editor_Audio_MuteMic", "Mikrofonu Sessize Al" },
        { "Editor_Audio_VolEnhance", "Ses Güçlendirme" },
        { "Editor_Audio_MicLevel", "Mikrofon Seviyesi" },
        { "Editor_Audio_NoiseReduction", "Gürültü Azaltma (Yapay Zeka)" },
        { "Editor_Audio_NoiseReductionDesc", "Arka plan gürültüsünü filtreler" },
        { "Editor_Audio_VocalEnhance", "Vokal Netleştirme" },
        { "Editor_Audio_VocalEnhanceDesc", "Ses netliğini ve frekansını yükseltir" },
        { "Editor_Keys_Title", "KISAYOL TUŞLARI" },
        { "Editor_Keys_DisplayKeys", "Kısayol Tuşlarını Göster" },
        { "Editor_Keys_DisplaySingleKey", "Tek Kısayol Tuşlarını Göster" },
        { "Editor_Keys_KeyStyle", "Tuş Tarzı" },
        { "Editor_Keys_Filled", "Dolu" },
        { "Editor_Keys_Outline", "Çerçeveli" },
        { "Editor_Keys_Minimal", "Minimal" },
        { "Editor_Keys_KeySize", "Tuş Boyutu" },
        { "Editor_Keys_ScreenPos", "Ekran Konumu" },
        { "Editor_Motion_Title", "HAREKET & BULANIKLIK" },
        { "Editor_Motion_MotionBlur", "Hareket Bulanıklığı" },
        { "Editor_Motion_ZoomBlur", "Zoom İçi Bulanıklık" },
        { "Editor_Motion_ScreenBlur", "Ekran Hareket Bulanıklığı" },
        { "Editor_Motion_CursorBlur", "İmleç Hareket Bulanıklığı" },
        { "Editor_Motion_CursorMovement", "İmleç Hareketi" },
        { "Editor_Motion_Slow", "Yavaş" },
        { "Editor_Motion_Medium", "Orta" },
        { "Editor_Motion_Fast", "Hızlı" },
        { "Editor_Camera_Title", "KAMERA YERLEŞİMİ" },
        { "Editor_Camera_Layer", "Kamera Katmanı" },
        { "Editor_Camera_Shape", "Kamera Şekli" },
        { "Editor_Camera_Circle", "Daire" },
        { "Editor_Camera_Square", "Kare" },
        { "Editor_Camera_Rounded", "Yuvarlak" },
        { "Editor_Volume_Title", "SES MİKSERİ" },
        { "Editor_Volume_MicLevel", "Mikrofon Seviyesi" },
        { "Editor_Volume_SysLevel", "Sistem Sesi Seviyesi" },
        { "Editor_Watermark_Title", "FİLİGRAN" },
        { "Editor_Watermark_Show", "Filigran Göster" },
        { "Editor_Watermark_Placeholder", "Filigran Metni" },
        { "Editor_Zoom_Title", "ZOOM ÖZELLİKLERİ" },
        { "Editor_Zoom_Factor", "Zoom Oranı" },
        { "Editor_Zoom_Start", "Başlangıç (sn)" },
        { "Editor_Zoom_End", "Bitiş (sn)" },
        { "Editor_Canvas_NoVideoMessage", "Video Dosyası Yüklenemedi" },
        { "Editor_Timeline_Undo", "Geri Al (Ctrl+Z)" },
        { "Editor_Timeline_Redo", "Yinele (Ctrl+Y)" },
        { "Editor_Timeline_Split", "Böl / Cut (S)" },
        { "Editor_Timeline_DeleteClip", "Kırpılan Parçayı / Efekti Sil (Del)" },
        { "Editor_Timeline_AddZoom", "Zoom Efekti Ekle (+)" },
        { "Editor_Timeline_MuteAll", "Tüm Sesleri Kapat/Aç" },
        { "Editor_Timeline_ZoomOut", "Timeline Daralt" },
        { "Editor_Timeline_ZoomIn", "Timeline Genişlet (Ctrl+Tekerlek)" },
        { "Editor_Timeline_TrackVideo", "Video Parçası" },
        { "Editor_Timeline_TrackVideoSub", "Ekran Kaydı" },
        { "Editor_Timeline_MuteVideoTrack", "Video Sesini Kapat/Aç" },
        { "Editor_Timeline_TrackAudio", "Ses Parçası" },
        { "Editor_Timeline_TrackAudioSub", "Dalga Formu / Mikrofon" },
        { "Editor_Timeline_MuteAudioTrack", "Ses Parçasını Kapat/Aç" },
        { "Editor_Timeline_TrackZoom", "Zoom Efektleri" },

        // Export
        { "Export_Title", "Videonuz Dışa Aktarılıyor..." },
        { "Export_Desc", "Lütfen uygulamayı kapatmayın. Tahmini kalan süre: " },
        { "Export_Calculating", "Hesaplanıyor..." },
        { "Export_Starting", "FFmpeg işlemi başlatılıyor..." },
        { "Export_Cancel", "Dışa Aktarmayı İptal Et" },
        { "Export_CancelConfirmTitle", "İptal Onayı" },
        { "Export_CancelConfirm", "Dışa aktarma işlemini iptal etmek istediğinizden emin misiniz?" },
        { "Export_SuccessTitle", "Dışa Aktarma Tamamlandı!" },
        { "Export_SuccessDesc", "Videonuz başarıyla oluşturuldu." },
        { "Export_OpenFolder", "Klasörde Göster" },
        { "Export_BackToEditor", "Editöre Dön" },

        // Library
        { "Library_Nav_Dashboard", "Kayıt Paneli" },
        { "Library_Nav_Title", "Proje Kütüphanesi" },
        { "Library_Refresh", "Yenile" },
        { "Library_Title", "Kayıtlı Projeler" },
        { "Library_Desc", "Tüm ekran kayıtlarınızı görüntüleyin, düzenleyin veya dışa aktarın." },
        { "Library_Empty_Title", "Henüz Kayıtlı Proje Yok" },
        { "Library_Empty_Desc", "Yeni bir ekran kaydı başlattığınızda projeleriniz burada listelenecektir." },
        { "Library_Btn_Edit", "Düzenle" },
        { "Library_Btn_Export", "Dışa Aktar" },
        { "Library_Btn_OpenFolder", "Klasörde Aç" },
        { "Library_Btn_Delete", "Sil" },

        // RecordingBarWindow
        { "RecBar_Status", "KAYIT" },
        { "RecBar_Pause", "Duraklat / Devam Et" },
        { "RecBar_Finish", "Kaydı Tamamla ve Düzenleyiciye Geç" },
        { "RecBar_Loading", "Yükleniyor..." },
        { "RecBar_Cancel", "Kaydı İptal Et" },

        // RecordingSetupToolbarWindow
        { "Setup_Close", "Kapat ve Dashboard'a Dön" },
        { "Setup_FullScreen", "Tam Ekran Kaydı" },
        { "Setup_ZoomEffect", "Zoom Efekti" },
        { "Setup_ZoomNone", "Yok" },
        { "Setup_Zoom2D", "2D Zoom" },
        { "Setup_Zoom3D", "3D Hareket" },
        { "Setup_Countdown", "Geri Sayım Süresi" },
        { "Setup_Count3s", "3 saniye" },
        { "Setup_Count5s", "5 saniye" },
        { "Setup_CountNone", "Geri sayım yok" },
        { "Setup_HideIcons", "Masaüstü Simgelerini Gizle" },
        { "Setup_HideTaskbar", "Görev Çubuğunu Gizle" },
        { "Setup_MoreSettings", "Daha Fazla Ayar" },
        { "Setup_Camera", "Kamera" },
        { "Setup_Mic", "Mikrofon" },
        { "Setup_Start", "Kayıt Başlat" },

        // RegionSelectionWindow
        { "Region_Title", "Bölge Seçimi" },
        { "Region_Instruction", "Kayıt Alınacak Bölgeyi Seçin" },
        { "Region_CancelHint", "İptal etmek için ESC'ye basın" },

        // CountdownWindow
        { "Countdown_Status", "Kayıt Başlıyor..." },

        // CameraOverlayWindow
        { "Camera_Title", "Kamera Önizleme" },
        { "Camera_Active", "Kamera Aktif" },
        { "Camera_ToggleShape", "Şekil Değiştir" },
        { "Camera_Close", "Kapat" },

        // TeleprompterWindow
        { "Teleprompter_Title", "Teleprompter" },
        { "Teleprompter_DragHint", "(Sürükleyip konumlandırabilirsiniz)" },
        { "Teleprompter_Placeholder", "Buraya konuşma metninizi veya notlarınızı yazın ya da yapıştırın..." },
        { "Teleprompter_Play", "Oynat / Duraklat" },
        { "Teleprompter_Start", "Başlat" },
        { "Teleprompter_Pause", "Duraklat" },
        { "Teleprompter_Size", "Boyut:" },
        { "Teleprompter_SpeedLabel", "Hız:" },
        { "Teleprompter_Reset", "Başa Dön" },
        { "Teleprompter_FontSize", "Yazı Boyutu" },
        { "Teleprompter_Speed", "Kaydırma Hızı" }
    };

    private readonly Dictionary<string, string> _en = new(StringComparer.OrdinalIgnoreCase)
    {
        // General & Common
        { "AppTitle", "ScreenPowerPro" },
        { "Save", "Save" },
        { "Cancel", "Cancel" },
        { "Delete", "Delete" },
        { "Close", "Close" },
        { "Back", "Back" },
        { "Success", "Success" },
        { "Error", "Error" },
        { "Warning", "Warning" },
        { "Loading", "Loading..." },
        { "Reset", "Reset" },
        { "None", "None" },
        { "Default", "Default" },
        { "Browse", "Browse" },
        { "Open", "Open" },
        { "Rename", "Rename" },
        { "Refresh", "Refresh" },
        { "Format", "Format" },
        { "Resolution", "Resolution" },
        { "Fps", "Frame Rate (FPS)" },

        // Dashboard
        { "Dashboard_Header_History", "History" },
        { "Dashboard_Header_ProjectManager", "Project Manager" },
        { "Dashboard_Header_Settings", "Settings" },
        { "Dashboard_Header_Teleprompter", "Teleprompter" },
        { "Dashboard_Subtitle", "What would you like to record?" },
        { "Dashboard_Mode_Screen", "Screen" },
        { "Dashboard_Mode_Screen_Desc", "Captures the entire primary display in high definition." },
        { "Dashboard_Mode_Custom", "Custom Area" },
        { "Dashboard_Mode_Custom_Desc", "Select a precise pixel-perfect region of the screen." },
        { "Dashboard_Mode_Window", "App Window" },
        { "Dashboard_Mode_Window_Desc", "Target a specific active application or desktop window." },
        { "Dashboard_Mode_Camera", "Camera Only" },
        { "Dashboard_Mode_Camera_Desc", "Record standalone webcam feed in full or circular mode." },
        { "Dashboard_Device_Camera", "Camera" },
        { "Dashboard_Device_Mic", "Microphone" },
        { "Dashboard_Device_SystemAudio", "System Audio" },
        { "Dashboard_StartRecording", "Start Recording" },
        { "Dashboard_SelectWindow", "Select Window" },
        { "Dashboard_OnlyAppAudio", "Only App Audio" },
        { "Dashboard_OnlyAppCount", "Only App ({0})" },
        { "Dashboard_NoAudioApps", "No active audio apps found" },
        { "Dashboard_AllSystemAudio", "All System Audio (Default)" },
        { "Dashboard_History_Title", "Recording History" },
        { "Dashboard_History_TabRecordings", "Recordings" },
        { "Dashboard_History_TabShared", "Shared" },
        { "Dashboard_History_Empty", "No recorded projects found yet." },
        { "Dashboard_History_SharedEmpty", "No sharing history available." },
        { "Dashboard_History_Open", "Open Project" },
        { "Dashboard_History_Rename", "Rename" },
        { "Dashboard_History_ShowInFolder", "Show in Folder" },
        { "Dashboard_History_Delete", "Delete Project" },
        { "Dashboard_History_DeleteConfirm", "Are you sure you want to permanently delete \"{0}\" and all its recordings?" },
        { "Dashboard_History_RenamePrompt", "Enter new project name" },
        { "Dashboard_History_ImportVideo", "Import External Video" },

        // Settings (SettingsWindow & SettingsPage)
        { "Settings_Title", "Settings" },
        { "Settings_Tab_General", "General" },
        { "Settings_Tab_Record", "Record" },
        { "Settings_Tab_Shortcuts", "Shortcut Keys" },
        { "Settings_Tab_Export", "Export" },
        { "Settings_Language", "Application Language" },
        { "Settings_Language_TR", "Türkçe" },
        { "Settings_Language_EN", "English" },
        { "Settings_SaveLocation", "Save Location" },
        { "Settings_ExportLocation", "Export Location" },
        { "Settings_AutoStart", "Auto-start with Windows" },
        { "Settings_AutoPlay", "Auto-play Video in Editor" },
        { "Settings_ExcludeApp", "Exclude ScreenPowerPro from Recording" },
        { "Settings_Quality", "Recording Quality" },
        { "Settings_Quality_Ultra", "Ultra (Near Lossless)" },
        { "Settings_Quality_High", "High (Recommended)" },
        { "Settings_Quality_Medium", "Medium" },
        { "Settings_Quality_Low", "Low" },
        { "Settings_Fps", "Target Frame Rate (FPS)" },
        { "Settings_Resolution", "Recording Resolution" },
        { "Settings_ZoomEffect", "Default Zoom Effect" },
        { "Settings_Zoom_2D", "2D Zoom (Smooth)" },
        { "Settings_Zoom_3D", "3D Motion (Instant)" },
        { "Settings_Zoom_None", "None" },
        { "Settings_Countdown", "Pre-Recording Countdown Duration" },
        { "Settings_Countdown_None", "No countdown" },
        { "Settings_Countdown_3s", "3 seconds" },
        { "Settings_Countdown_5s", "5 seconds" },
        { "Settings_Countdown_10s", "10 seconds" },
        { "Settings_HideDesktopIcons", "Hide Desktop Icons During Recording" },
        { "Settings_HideTaskbar", "Hide Taskbar During Recording" },
        { "Settings_HideMouseCursor", "Hide Mouse Cursor in Raw Recording" },
        { "Settings_Shortcut_StartStop", "Start / Stop Recording Shortcut" },
        { "Settings_Shortcut_Pause", "Pause / Resume Recording Shortcut" },
        { "Settings_Shortcut_Screenshot", "Take Screenshot Shortcut" },
        { "Settings_ExportFormat", "Default Export Format" },
        { "Settings_ExportResolution", "Default Export Resolution" },
        { "Settings_SaveBtn", "Save Settings" },
        { "Settings_SavedSuccess", "Settings saved successfully." },

        // Editor
        { "Editor_Nav_Back", "Dashboard" },
        { "Editor_Nav_Save", "Save" },
        { "Editor_Nav_Export", "Export" },
        { "Editor_Nav_Saved", "Project Saved" },
        { "Editor_Sidebar_Cursor", "Cursor Settings" },
        { "Editor_Sidebar_Canvas", "Canvas Size & Style" },
        { "Editor_Sidebar_Audio", "Microphone & Audio" },
        { "Editor_Sidebar_Keys", "Shortcut Keys" },
        { "Editor_Sidebar_Motion", "Motion & Blur" },
        { "Editor_Sidebar_Camera", "Camera Overlay" },
        { "Editor_Sidebar_Volume", "Audio Mixer" },
        { "Editor_Sidebar_Watermark", "Watermark" },
        { "Editor_Sidebar_Zoom", "Zoom Properties" },
        { "Editor_Cursor_Title", "CURSOR SETTINGS" },
        { "Editor_Cursor_Show", "Show Cursor" },
        { "Editor_Cursor_Size", "Cursor Size" },
        { "Editor_Cursor_Style", "Cursor Style" },
        { "Editor_Cursor_ClickEffect", "Click Effect" },
        { "Editor_Cursor_ClickEffect_None", "None" },
        { "Editor_Cursor_ClickEffect_Default", "Default" },
        { "Editor_Cursor_ClickEffect_Ripple", "Ripple" },
        { "Editor_Cursor_ClickEffect_Ring", "Ring" },
        { "Editor_Cursor_ClickEffect_Diffusion", "Diffusion" },
        { "Editor_Cursor_ClickEffect_Spotlight", "Spotlight" },
        { "Editor_Cursor_ClickEffect_Sparkle", "Sparkle" },
        { "Editor_Cursor_ClickEffect_Firework", "Firework" },
        { "Editor_Cursor_ClickEffect_Christmas", "Christmas" },
        { "Editor_Cursor_ClickSound", "Play Click Sound" },
        { "Editor_Cursor_HideIdle", "Hide Cursor When Idle" },
        { "Editor_Cursor_RawInfoTitle", "Raw Recording Cursor" },
        { "Editor_Cursor_RawInfoDesc", "When 'Hide Cursor In Raw Recording' is enabled during recording, original cursor is hidden and only custom cursor styled here will be visible." },
        { "Editor_Canvas_Title", "CANVAS SIZE & STYLE" },
        { "Editor_Canvas_AspectRatio", "Aspect Ratio" },
        { "Editor_Canvas_Auto", "Auto" },
        { "Editor_Canvas_FixedZoom", "Fixed Zoom Part" },
        { "Editor_Canvas_Padding", "Padding" },
        { "Editor_Canvas_Inset", "Inset" },
        { "Editor_Canvas_Roundness", "Corner Roundness" },
        { "Editor_Canvas_Shadow", "Shadow" },
        { "Editor_Canvas_BgPreset", "Background Presets" },
        { "Editor_Canvas_PresetDefault", "Default" },
        { "Editor_Canvas_PresetSteady", "Steady" },
        { "Editor_Canvas_PresetGraceful", "Grace" },
        { "Editor_Canvas_PresetScenery", "Scene" },
        { "Editor_Canvas_Opacity", "Opacity" },
        { "Editor_Audio_Title", "MICROPHONE AUDIO" },
        { "Editor_Audio_MuteMic", "Mute Microphone" },
        { "Editor_Audio_VolEnhance", "Volume Enhancement" },
        { "Editor_Audio_MicLevel", "Microphone Level" },
        { "Editor_Audio_NoiseReduction", "Noise Reduction (AI)" },
        { "Editor_Audio_NoiseReductionDesc", "Filters background noise" },
        { "Editor_Audio_VocalEnhance", "Vocal Enhancement" },
        { "Editor_Audio_VocalEnhanceDesc", "Enhances vocal clarity and presence" },
        { "Editor_Keys_Title", "SHORTCUT KEYS" },
        { "Editor_Keys_DisplayKeys", "Display Shortcut Keys" },
        { "Editor_Keys_DisplaySingleKey", "Display Single Shortcut Key" },
        { "Editor_Keys_KeyStyle", "Key Style" },
        { "Editor_Keys_Filled", "Filled" },
        { "Editor_Keys_Outline", "Outline" },
        { "Editor_Keys_Minimal", "Minimal" },
        { "Editor_Keys_KeySize", "Key Size" },
        { "Editor_Keys_ScreenPos", "Screen Position" },
        { "Editor_Motion_Title", "MOTION & BLUR" },
        { "Editor_Motion_MotionBlur", "Motion Blur" },
        { "Editor_Motion_ZoomBlur", "Zoom-in Motion Blur" },
        { "Editor_Motion_ScreenBlur", "Screen Motion Blur" },
        { "Editor_Motion_CursorBlur", "Cursor Motion Blur" },
        { "Editor_Motion_CursorMovement", "Cursor Movement" },
        { "Editor_Motion_Slow", "Slow" },
        { "Editor_Motion_Medium", "Medium" },
        { "Editor_Motion_Fast", "Fast" },
        { "Editor_Camera_Title", "CAMERA OVERLAY" },
        { "Editor_Camera_Layer", "Camera Layer" },
        { "Editor_Camera_Shape", "Camera Shape" },
        { "Editor_Camera_Circle", "Circle" },
        { "Editor_Camera_Square", "Square" },
        { "Editor_Camera_Rounded", "Rounded" },
        { "Editor_Volume_Title", "AUDIO MIXER" },
        { "Editor_Volume_MicLevel", "Microphone Level" },
        { "Editor_Volume_SysLevel", "System Audio Level" },
        { "Editor_Watermark_Title", "WATERMARK" },
        { "Editor_Watermark_Show", "Show Watermark" },
        { "Editor_Watermark_Placeholder", "Watermark Text" },
        { "Editor_Zoom_Title", "ZOOM PROPERTIES" },
        { "Editor_Zoom_Factor", "Zoom Factor" },
        { "Editor_Zoom_Start", "Start (sec)" },
        { "Editor_Zoom_End", "End (sec)" },
        { "Editor_Canvas_NoVideoMessage", "Failed to Load Video File" },
        { "Editor_Timeline_Undo", "Undo (Ctrl+Z)" },
        { "Editor_Timeline_Redo", "Redo (Ctrl+Y)" },
        { "Editor_Timeline_Split", "Split / Cut (S)" },
        { "Editor_Timeline_DeleteClip", "Delete Trimmed Clip / Effect (Del)" },
        { "Editor_Timeline_AddZoom", "Add Zoom Effect (+)" },
        { "Editor_Timeline_MuteAll", "Mute / Unmute All Audio" },
        { "Editor_Timeline_ZoomOut", "Zoom Out Timeline" },
        { "Editor_Timeline_ZoomIn", "Zoom In Timeline (Ctrl+Wheel)" },
        { "Editor_Timeline_TrackVideo", "Video Track" },
        { "Editor_Timeline_TrackVideoSub", "Screen Recording" },
        { "Editor_Timeline_MuteVideoTrack", "Mute / Unmute Video Track" },
        { "Editor_Timeline_TrackAudio", "Audio Track" },
        { "Editor_Timeline_TrackAudioSub", "Waveform / Mic" },
        { "Editor_Timeline_MuteAudioTrack", "Mute / Unmute Audio Track" },
        { "Editor_Timeline_TrackZoom", "Zoom Effects" },

        // Export
        { "Export_Title", "Exporting Your Video..." },
        { "Export_Desc", "Please do not close the app. Estimated time remaining: " },
        { "Export_Calculating", "Calculating..." },
        { "Export_Starting", "Starting FFmpeg process..." },
        { "Export_Cancel", "Cancel Export" },
        { "Export_CancelConfirmTitle", "Confirm Cancel" },
        { "Export_CancelConfirm", "Are you sure you want to cancel the export?" },
        { "Export_SuccessTitle", "Export Completed!" },
        { "Export_SuccessDesc", "Your video has been rendered successfully." },
        { "Export_OpenFolder", "Show in Folder" },
        { "Export_BackToEditor", "Back to Editor" },

        // Library
        { "Library_Nav_Dashboard", "Dashboard" },
        { "Library_Nav_Title", "Project Library" },
        { "Library_Refresh", "Refresh" },
        { "Library_Title", "Recorded Projects" },
        { "Library_Desc", "View, edit, or export all your screen recordings." },
        { "Library_Empty_Title", "No Recorded Projects Yet" },
        { "Library_Empty_Desc", "When you start a new recording, your projects will appear here." },
        { "Library_Btn_Edit", "Edit" },
        { "Library_Btn_Export", "Export" },
        { "Library_Btn_OpenFolder", "Open Folder" },
        { "Library_Btn_Delete", "Delete" },

        // RecordingBarWindow
        { "RecBar_Status", "REC" },
        { "RecBar_Pause", "Pause / Resume" },
        { "RecBar_Finish", "Finish Recording and Open Editor" },
        { "RecBar_Loading", "Loading..." },
        { "RecBar_Cancel", "Cancel Recording" },

        // RecordingSetupToolbarWindow
        { "Setup_Close", "Close and Return to Dashboard" },
        { "Setup_FullScreen", "Full Screen Recording" },
        { "Setup_ZoomEffect", "Zoom Effect" },
        { "Setup_ZoomNone", "None" },
        { "Setup_Zoom2D", "2D Zoom" },
        { "Setup_Zoom3D", "3D Motion" },
        { "Setup_Countdown", "Countdown Duration" },
        { "Setup_Count3s", "3 seconds" },
        { "Setup_Count5s", "5 seconds" },
        { "Setup_CountNone", "No countdown" },
        { "Setup_HideIcons", "Hide Desktop Icons" },
        { "Setup_HideTaskbar", "Hide Taskbar" },
        { "Setup_MoreSettings", "More Settings" },
        { "Setup_Camera", "Camera" },
        { "Setup_Mic", "Microphone" },
        { "Setup_Start", "Start Recording" },

        // RegionSelectionWindow
        { "Region_Title", "Region Selection" },
        { "Region_Instruction", "Select Region to Record" },
        { "Region_CancelHint", "Press ESC to cancel" },

        // CountdownWindow
        { "Countdown_Status", "Recording Starting..." },

        // CameraOverlayWindow
        { "Camera_Title", "Camera Preview" },
        { "Camera_Active", "Camera Active" },
        { "Camera_ToggleShape", "Change Shape" },
        { "Camera_Close", "Close" },

        // TeleprompterWindow
        { "Teleprompter_Title", "Teleprompter" },
        { "Teleprompter_DragHint", "(Drag to reposition)" },
        { "Teleprompter_Placeholder", "Type or paste your speech text or notes here..." },
        { "Teleprompter_Play", "Play / Pause" },
        { "Teleprompter_Start", "Start" },
        { "Teleprompter_Pause", "Pause" },
        { "Teleprompter_Size", "Size:" },
        { "Teleprompter_SpeedLabel", "Speed:" },
        { "Teleprompter_Reset", "Reset Scroll" },
        { "Teleprompter_FontSize", "Font Size" },
        { "Teleprompter_Speed", "Scroll Speed" }
    };

    public LocalizationService(SettingsService settingsService)
    {
        _settingsService = settingsService;
        _currentLanguage = string.Equals(_settingsService.Current.Language, "en", StringComparison.OrdinalIgnoreCase) ? "en" : "tr";
    }

    public string this[string key] => Get(key);

    public string Get(string key, params object[] args)
    {
        var dict = _currentLanguage == "en" ? _en : _tr;
        if (!dict.TryGetValue(key, out var val))
        {
            if (!_tr.TryGetValue(key, out val) && !_en.TryGetValue(key, out val))
            {
                val = key;
            }
        }

        if (args != null && args.Length > 0)
        {
            try
            {
                return string.Format(val, args);
            }
            catch
            {
                return val;
            }
        }
        return val;
    }

    public void SetLanguage(string langCode)
    {
        string normalized = string.Equals(langCode, "en", StringComparison.OrdinalIgnoreCase) ? "en" : "tr";
        if (_currentLanguage == normalized) return;

        _currentLanguage = normalized;
        _settingsService.Current.Language = normalized;
        _settingsService.Save();

        LanguageChanged?.Invoke();
    }
}
