/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        secondary: '#ffb2b7',
        'on-primary': '#1000a9',
        'surface-variant': '#34343c',
        error: '#ffb4ab',
        outline: '#908fa0',
        'on-surface': '#e3e1ec',
        'on-background': '#e3e1ec',
        'on-secondary-container': '#ffc2c4',
        'outline-variant': '#464554',
        background: '#12131a',
        primary: '#c0c1ff',
        surface: '#12131a',
        'surface-container': '#1e1f27',
        'surface-container-lowest': '#0d0e15',
        'surface-container-low': '#1a1b22',
        'surface-container-high': '#292931',
        'surface-container-highest': '#34343c',
        'surface-bright': '#383941',
        'primary-container': '#8083ff',
        'on-primary-container': '#0d0096',
        tertiary: '#d0bcff',
        'tertiary-container': '#a078ff',
        'on-surface-variant': '#c7c4d7',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        'toolbar-height': '48px',
        'sidebar-width': '260px',
        'panel-gap': '16px',
        'container-margin': '24px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
